#!/usr/bin/env ruby
require 'date'

def exit_with_usage_instructions
  puts <<EOS
I'd cheer for you, if only I knew who you were :(
Try again with `./cheers [Name] [MM/DD Birthday]
EOS
  exit
end


def message_invalid_birthday
  puts "I would wish you a Happy Birthday, if I knew when that was!"
end


###starts accepting arguments

exit_with_usage_instructions if ARGV.empty? || ARGV.size > 2


original_name = ARGV[0]
cheerable_name = original_name.upcase.gsub(/[^A-Z]/, "")

exit_with_usage_instructions if cheerable_name.empty?

cheerable_name.each_char do |char|
  article = "n" if "AEFHILMNORSX".include? char
  puts "Give me a#{article}... #{char}"
end
puts "#{original_name}'s just GRAND!"
puts ""


##starts dealing with birthdays

def birthday_wish(num)
  bday = Date.parse(num)
  present_date = Date.today
  days_away = (bday - present_date) % 365
  days_away.to_i
end

  bday = ARGV[1]


  if bday.nil? || bday.length > 5
    message_invalid_birthday
  else
    begin
      days_away = birthday_wish(bday)
      puts "Awesome! Your birthday's in #{days_away} days! Happy Birthday in advance!"
    rescue
      message_invalid_birthday
    end

  end

